/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhySsaRouteImport } from './routes/why-ssa'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhySsaRoute = WhySsaRouteImport.update({
  id: '/why-ssa',
  path: '/why-ssa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRoute
  '/products': typeof ProductsRoute
  '/publications': typeof PublicationsRoute
  '/services': typeof ServicesRoute
  '/why-ssa': typeof WhySsaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRoute
  '/products': typeof ProductsRoute
  '/publications': typeof PublicationsRoute
  '/services': typeof ServicesRoute
  '/why-ssa': typeof WhySsaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRoute
  '/products': typeof ProductsRoute
  '/publications': typeof PublicationsRoute
  '/services': typeof ServicesRoute
  '/why-ssa': typeof WhySsaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/insights'
    | '/products'
    | '/publications'
    | '/services'
    | '/why-ssa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/insights'
    | '/products'
    | '/publications'
    | '/services'
    | '/why-ssa'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/insights'
    | '/products'
    | '/publications'
    | '/services'
    | '/why-ssa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InsightsRoute: typeof InsightsRoute
  ProductsRoute: typeof ProductsRoute
  PublicationsRoute: typeof PublicationsRoute
  ServicesRoute: typeof ServicesRoute
  WhySsaRoute: typeof WhySsaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-ssa': {
      id: '/why-ssa'
      path: '/why-ssa'
      fullPath: '/why-ssa'
      preLoaderRoute: typeof WhySsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InsightsRoute: InsightsRoute,
  ProductsRoute: ProductsRoute,
  PublicationsRoute: PublicationsRoute,
  ServicesRoute: ServicesRoute,
  WhySsaRoute: WhySsaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
